services:
  php:
    build: ./php/
    command: php artisan serve --host=0.0.0.0 --port=8000
    container_name: travel-php
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    volumes:
      - ./src/laravel/:/var/www/html/laravel/:rw
    working_dir: /var/www/html/laravel/

  mysql:
    container_name: travel-mysql
    env_file:
      - ./.env
    # expose:
    #   - 3306
    image: mysql:8.4
  phpmyadmin:
    container_name: travel-phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_HOST=travel-mysql
      - PMA_PORT=3306
      - PMA_SSL=1
    image: phpmyadmin:5-apache
    ports:
      - "8081:80"